# Generated by Django 5.0.6 on 2024-06-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_product_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('passport_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.passport')),
            ],
        ),
    ]
