# Generated by Django 5.0.6 on 2024-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_author_blog_tag_entry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='students_pe_name_06607c_idx'),
        ),
    ]
